### ISSUE TITLE
ValueStateMachineExample not working

### ISSUE THREAD

**Issue by gitanuj** [atomix/copycat#166]
ValueStateMachineExample expects args[0] and args[1] as Integer. However it also expects args[1] in the format 'host:port' because it uses split operation on it in the for loop.

**Comment by kuujo** [comment]
Fixed, but this needs to be better documented. I updated the examples to follow the same structure as the Atomix examples. The servers take a log directory, local host:port, and remote hosts:ports:
```
java -jar target/value-state-machine.jar logs/server1 localhost:5000 localhost:5001 localhost:5002
java -jar target/value-state-machine.jar logs/server2 localhost:5001 localhost:5000 localhost:5002
java -jar target/value-state-machine.jar logs/server3 localhost:5002 localhost:5000 localhost:5000
```

The client takes a list of server hosts:ports:
```
java -jar target/value-client.jar localhost:5000 localhost:5001 localhost:5002
```
