### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jameshuang** [atomix/copycat#211]
One of the previous issues #16 suggested the following steps:

Downloaded maven
Cloned this repo to my computer
cd'd into the root directory of this repo
ran 'mvn clean install'

But it failed here like this:

......
[INFO] Reactor Summary:
[INFO] 
[INFO] Copycat Parent Pom ................................ SUCCESS [2.105s]
[INFO] Copycat Protocol .................................. FAILURE [0.657s]
[INFO] Copycat Server .................................... SKIPPED
[INFO] Copycat Client .................................... SKIPPED
[INFO] Copycat Raft Tests ................................ SKIPPED
[INFO] Copycat Examples Parent ........................... SKIPPED
[INFO] Copycat State Machine Example ..................... SKIPPED
[INFO] Copycat Client Example ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.897s
[INFO] Finished at: Fri Apr 08 16:56:40 PDT 2016
[INFO] Final Memory: 20M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project copycat-protocol: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :copycat-protocol

Can anybody help me please? The code is the latest.

**Comment by jameshuang** [comment]
OK, it seems that it was asking for Java 1.8. I was using 1.7.

**Comment by kuujo** [comment]
Right. All Atomix projects depend on Java 8

**Comment by jameshuang** [comment]
Thanks. By the way, does CopyCat run well on JamVM (or any other OpenJDK VMs)?
