### ISSUE TITLE
Missing copyright information in source distribution

### ISSUE THREAD

**Issue by arp7** [atomix/copycat#213]
The template in the [LICENSE](https://github.com/atomix/copycat/blob/master/LICENSE#L189) file should be filled out so redistributions can correctly credit the copyright owners.

        Copyright {yyyy} {name of copyright owner}

**Comment by kuujo** [comment]
Actually, that copyright notice is what you apply to the code, and it *is* properly applied to all class files. It just needed to be removed from the `LICENSE` file. Thanks!
