### ISSUE TITLE
Fast async calls cause errors

### ISSUE THREAD

**Issue by ccleve** [atomix/copycat#248]
I've written a plain vanilla hello world test app with a single server and a single client. When I use client code like this:

for (int i = 0; i < 10; i++) {
    PutCommand pc = new PutCommand("key" + i, "value" + i);
    client.submit(pc);
}

I get _server-side_ errors, and the state machine never gets called.

2016-09-19 17:26:13 DESKTOP-KVRE8GD io.atomix.copycat.server.state.LeaderState 23106 DEBUG /127.0.0.1:5000 - Received CommandRequest[session=3, sequence=10, command=com.dieselpoint.dieseldb.atomix.PutCommand@5edce47c]
2016-09-19 17:26:13 DESKTOP-KVRE8GD io.atomix.copycat.server.state.LeaderState 23111 DEBUG /127.0.0.1:5000 - Sent CommandResponse[status=ERROR, index=0, eventIndex=0, result=null]

(Weirdly, in the 10 errors the sequence= starts at 10 and goes down to 1).

On the other hand, when I use this line:

client.submit(pc).get();

everything works fine. It also works fine if I add a 10 ms delay between calls:

client.submit(pc);
Thread.sleep(10);

Have I hit a race condition? Is this a bug?

**Comment by ronenhamias** [comment]
what is the status of this issue was it resolved?

**Comment by aliasneo015** [comment]
No, this is not a bug. client.submit returns a Future. The client's thread which called the submit would ideally wait for all the submitted commands to finish (via .join()).
Simple modification (this it just to show what I am talking about)

List<CompletableFuture<?>> list = new ArrayList<>();
for (int i = 0; i < 10; i++) {
    PutCommand pc = new PutCommand("key" + i, "value" + i);
    list.add(client.submit(pc));
}

for (CompletableFuture<?> f : list) {
    f.join();
}

**Comment by ccleve** [comment]
This looks like a dumb error on my part. My client program terminates before it receives a response. If I just leave it running a little longer everything works fine.
