### ISSUE TITLE
How to publish/set Commands on to StateMachine when server side

### ISSUE THREAD

**Issue by cdancy** [atomix/copycat#251]
We've got a jax-rs based front-end to our program that serves to take in data. What we want to do is take data sent over http and send that to the copycat server running in the same program so that its replicated to other similar nodes. The very high-level idea goes something like:
1. Take in data to be replicated over http.
2. Send data to CopycatServer to be replicated on other nodes.
3. Data can now be queried on node X.

However, after looking through the examples and code I can't see an easy way to accomplish this. Looks like I need to start/init a Session somehow to work with the StateMachine but I can't see a clean cut way to do so. Any suggestions? I'm using the "Map State Machine" example if that provides more context.

**Comment by kuujo** [comment]
So, this is actually exactly what's being built in Copycat/Atomix 2.0. But the current way to do it is do what Atomix does (or use Atomix):

Start a local `CopycatServer`. Then create a `CopycatClient` with a `LocalTransport` that connects to the local server. Then proxy HTTP requests through the client to the server, which will send them to the leader and replicate them and eventually apply them to the state machine. Use queries to read the state of the system. Code can be found in `AtomixReplica` to do this.

There are some deficiencies in this approach though. The biggest issue is that the HTTP requests won't be linearizable. They're only linearizable between the `CopycatClient` and `CopycatServer`. To guarantee linearizability, clients have to exchange indexes with the cluster over HTTP. This is why Atomix is building HTTP into the protocol. The way it will work is Atomix will support an `HttpProtocol` which is essentially a Raft client protocol that supports arbitrary HTTP requests. Then, state machines can be annotated with JAX-RS annotations. Requests received on the `HttpProtocol` are converted into Raft commands (`PUT`, `POST`, `DELETE`) and queries (`GET`) and are replicated before being applied to the state machine. This effectively results in the greatest level of guarantees as the HTTP API essentially *is* a replicated state machine where REST API requests themselves are logged and replicated. And I think the model fits well with REST concepts.

But with the current architecture of the system, that's not easy to do. The Copycat `2.0` branch will have the required abstractions, but it won't be stable for a while.
