### ISSUE TITLE
Leader to follower transition leading to committing the wrong entry

### ISSUE THREAD

**Issue by thiagoss** [atomix/copycat#268]
Certain timing when a server has appended an entry but not committed and then transitioning to follower can make this server commit a different entry (this one it appended) than the entry provided by the leader. Making this server stay in a different state than the rest of the servers.

**Comment by thiagoss** [comment]
[logs.zip](https://github.com/atomix/copycat/files/695161/logs.zip)

Logs for the issue. The problematic commit happens to index 780 of partition 2.

Search for: `/172.17.0.2:9876 - Appended CommandEntry[index=780, term=1, session=18, sequence=198, timestamp=1483752077971` in onos1 and then look at what gets committed in onos1 and onos2.

(Had to use .xz inside .zip for size issues as github doesn't recognize .xz as a valid file)

**Comment by kuujo** [comment]
This is fixed.
