### ISSUE TITLE
Bug in network partition detection logic?

### ISSUE THREAD

**Issue by madjam** [atomix/copycat#30]
Scenario 3 nodes: s1, s2 and s3
Kill s1 (current leader)
Noticed that s2 repeatedly gets elected leader and immediately steps down suspecting a network partition.

Here are the relevant logs for s2:

`13:35:35.542 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Heartbeat timed out in PT1.4S
13:35:35.542 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Polling members [Address[localhost/127.0.0.1:5001], Address[localhost/127.0.0.1:5003]]
13:35:35.542 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Polling Address[localhost/127.0.0.1:5001] for next term 114
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Polling Address[localhost/127.0.0.1:5003] for next term 114
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Received accepted poll from Address[localhost/127.0.0.1:5003]
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Transitioning to CANDIDATE
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.FollowerState - Address[localhost/127.0.0.1:5002] - Cancelling heartbeat timer
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Starting election
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Set term 114
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Voted for Address[localhost/127.0.0.1:5002]
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Requesting votes from [Address[localhost/127.0.0.1:5001], Address[localhost/127.0.0.1:5003]]
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Requesting vote from Address[localhost/127.0.0.1:5001] for term 114
13:35:35.543 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Requesting vote from Address[localhost/127.0.0.1:5003] for term 114
13:35:35.544 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Received successful vote from Address[localhost/127.0.0.1:5003]
13:35:35.544 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Transitioning to LEADER
13:35:35.544 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.c.server.state.CandidateState - Address[localhost/127.0.0.1:5002] - Cancelling election
13:35:35.544 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Found leader Address[localhost/127.0.0.1:5002]
13:35:35.560 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.LeaderState - Address[localhost/127.0.0.1:5002] - Sent AppendRequest[term=114, leader=2130712286, logIndex=742033, logTerm=1, entries=[325], commitIndex=787602, globalIndex=787570] to Address[localhost/127.0.0.1:5001]
13:35:35.575 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.LeaderState - Address[localhost/127.0.0.1:5002] - Sent AppendRequest[term=114, leader=2130712286, logIndex=742031, logTerm=1, entries=[327], commitIndex=787602, globalIndex=787570] to Address[localhost/127.0.0.1:5003]
13:35:35.575 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.LeaderState - Address[localhost/127.0.0.1:5002] - Starting heartbeat timer
13:35:35.575 [copycat-server-Address[localhost/127.0.0.1:5002]] WARN  i.a.copycat.server.state.LeaderState - Address[localhost/127.0.0.1:5002] - Suspected network partition. Stepping down
13:35:35.575 [copycat-server-Address[localhost/127.0.0.1:5002]] INFO  i.a.copycat.server.state.ServerState - Address[localhost/127.0.0.1:5002] - Transitioning to FOLLOWER
13:35:35.575 [copycat-server-Address[localhost/127.0.0.1:5002]] DEBUG i.a.copycat.server.state.LeaderState - Address[localhost/127.0.0.1:5002] - Cancelling heartbeat timer`

My hunch is that the [logic in place](https://github.com/atomix/copycat/blob/master/server/src/main/java/io/atomix/copycat/server/state/LeaderState.java#L1173-L1180) for a leader to detect if it is partitioned away is causing this.

When a AE request to a follower fails we immediately check to see if the leader is partitioned by checking when the last successful commit happened. I feel this check should include the time when the leader's term started.

So perhaps the check ought to be:

`System.currentTimeMillis() - Math.max(commitTime(), termStartTime) > context.getElectionTimeout().toMillis() * 2`

**Comment by kuujo** [comment]
Ahh good point. That makes sense.

The leader now also stores the index of its no-op entry which has to be committed before the leader will commit entries from previous terms. This could be used to prevent the leader from stepping down until it's able to commit an entry from its term. Essentially, the condition becomes `commitIndex >= leaderIndex`. Once the leader is able to commit its no-op entry we know it was able to talk to a majority and if that majority is lost the partition detection can cause the leader to step down.

But this approach does have the potential to prevent the leader from stepping down altogether if a follower crashes right when the leader is elected and the leader can't commit an entry from its term and so will never check for partitions. That doesn't cause any safety issues since if it can't commit its no-op entry it can't commit commands either, but it's something to think about.

I think storing and using the term start time is probably fine since it won't prevent the leader from stepping down in that scenario.
